[package]
name = "universal_convert"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-multipart = "0.7.2"
actix-web = "4.12.1"
futures = "0.3.31"
image = "0.25.9"
tokio = "1.48.0"
uuid = {version = "1.18.1", features = ["v4"]}
